[window]
dynamic_padding = true
padding.x = 1
padding.y = 0
opacity = 0.75
decorations = "none"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1d1d1d"
foreground = "#fff4d2"

[colors.cursor]
text = "#bdae93"
cursor ="#665c54"

[colors.normal]
black = "#1d2021"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#a89984"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#fff4d2"

[font]
size = 11
offset.x=0
offset.y=1

[font.normal]
family = "IntoneMono Nerd Font"
style = "Normal"
#family = "IntoneMono Nerd Font"
#style = "Medium"
[font.bold]
family = "IntoneMono Nerd Font"
style = "Normal"
[font.italic]
family = "IntoneMono Nerd Font"
style = "Normal"
[font.bold_italic]
family = "IntoneMono Nerd Font"
style = "Normal"
